import moment from "moment"

export default () => ({
    id: null,
    status: null,
    status_set_at: null,
    number: null,
    contractor_id: null,
    date: moment().format('YYYY-MM-DD'),
    comment: null,
    legal_entity_id: null,
    invoice_files: [],
    payment_method_id: null,
    payment_status: 0,
    payment_history: [],
    payment_confirm: 0,
    payment_date: null,
    payment_order_date: null,
    debt_payment: 0,
    payment_files: [],
    delivery_type: null,
    products: [],
    new_products: [],
    is_edo: null,
    deleted_products:[],
    refunds:[],
    refundAvailableProducts: [],
    refuses_history: [],
    transactions: [],
    created_at: null,
    updated_at: null,
    files: {
        new_invoice_files: [],
        deleted_invoice_files: [],
        new_payment_files: [],
        deleted_payment_files: [],
    },

    isNew: true,
    original: {},
})
